# Generated by Django 4.2.7 on 2023-11-20 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя', max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(help_text='Введите свой действующий адрес электронной почты', max_length=100, verbose_name='Email')),
                ('subject', models.CharField(help_text='Введите тему сообщения', max_length=400, verbose_name='Тема')),
                ('message', models.TextField(help_text='Введите сообщение', verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('is_read', models.BooleanField(default=False, verbose_name='Отметка о прочитанном сообщении')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(help_text='Введите почту', max_length=50, verbose_name='Почта')),
                ('phone', models.CharField(help_text='Введите телефон', max_length=50, verbose_name='Телефон')),
                ('instagram', models.URLField(blank=True, help_text='Instagram', max_length=150, null=True, verbose_name='Instagram')),
                ('github', models.URLField(blank=True, help_text='Github', max_length=150, null=True, verbose_name='Github')),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn', max_length=150, null=True, verbose_name='LinkedIn')),
                ('telegram', models.URLField(blank=True, help_text='Telegram', max_length=150, null=True, verbose_name='Telegram')),
                ('education', models.TextField(blank=True, help_text='Образование', null=True, verbose_name='Образование')),
                ('work_history', models.TextField(blank=True, help_text='Опыт работы', null=True, verbose_name='Опыт работы')),
            ],
            options={
                'verbose_name': 'Обо мне',
                'verbose_name_plural': 'Обо мне',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(help_text='Введите название услуги', max_length=100, verbose_name='Услуга')),
                ('description', models.TextField(help_text='Введите описание услуги', verbose_name='Описание услуги')),
                ('rate_per_hour', models.DecimalField(decimal_places=2, help_text='Введите стоимость в долларах за час', max_digits=10, verbose_name='Стоимость за час')),
                ('estimated_time', models.DecimalField(decimal_places=2, help_text='Оцените, сколько часов требуется для выполнения услуги', max_digits=10, verbose_name='Оценка времени')),
            ],
            options={
                'verbose_name': 'Расценка',
                'verbose_name_plural': 'Расценки',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='Загрузите файл, если необходимо', null=True, upload_to='project_file/', verbose_name='Файл проекта')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение, если есть', null=True, upload_to='project_image/', verbose_name='Изображение проекта')),
                ('title', models.CharField(help_text='Введите название проекта', max_length=150, verbose_name='Название проекта')),
                ('description', models.TextField(help_text='Введите описание проекта', verbose_name='Описание проекта')),
                ('start_date', models.DateField(help_text='Введите дату начала', verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, help_text='Введите дату окончания, если завершён', null=True, verbose_name='Дата окончания')),
                ('url', models.URLField(blank=True, help_text='Введите ссылку на проект', max_length=150, null=True, verbose_name='Ссылка на проект')),
                ('repository', models.URLField(blank=True, help_text='Введите репозиторий GitHub', max_length=150, null=True, verbose_name='GitHub репозиторий')),
                ('technologies_used', models.CharField(help_text='Введите технологии, используемые в проекте', max_length=300, verbose_name='Использованные технологии')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('programming', 'Программирование'), ('design', 'Дизайн'), ('languages', 'Языки программирования'), ('database', 'Базы данных'), ('frameworks', 'Фреймворки'), ('tools', 'Инструменты разработки'), ('soft_skills', 'Soft Skills'), ('web', 'Веб-разработка'), ('mobile', 'Мобильная разработка'), ('cloud', 'Облачные технологии'), ('testing', 'Тестирование и QA'), ('analytics', 'Аналитика данных'), ('machine_learning', 'Машинное обучение и искусственный интеллект'), ('security', 'Информационная безопасность'), ('networking', 'Сетевые технологии'), ('graphics', 'Графический дизайн'), ('audio_video', 'Аудио и видео производство'), ('project_management', 'Управление проектами'), ('communication', 'Коммуникационные навыки'), ('leadership', 'Лидерство'), ('entrepreneurship', 'Предпринимательство'), ('data_science', 'Наука о данных'), ('automation', 'Автоматизация процессов'), ('devops', 'DevOps'), ('blockchain', 'Блокчейн технологии'), ('robotics', 'Робототехника'), ('language', 'Знание языков')], help_text='Выберите категорию для навыка', max_length=50, verbose_name='Категория')),
                ('name', models.CharField(help_text='Введите название навыка', max_length=50, verbose_name='Навык')),
                ('percentage', models.IntegerField(help_text='Введите процент знаний навыка', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент знаний')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
    ]
